stages:
  - build
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o main

deploy:
  stage: deploy
  image: python:3.7
  before_script:
    - pip install awscli
  script:
    - aws lambda create-function --function-name $LAMBDA_FUNCTION_NAME --runtime go1.x --role arn:aws:lambda:us-east-1:360833390362:function:GoLambda --zip-file fileb://main
