image: golang:1.16

variables:
  ZIP_FILENAME: lambda-package.zip

stages:
  - build
  - package
  - deploy

before_script:
  - go mod download

build:
  stage: build
  script:
    - go build -o main

package:
  stage: package
  script:
    - apt-get update && apt-get -y install zip
    - zip -r $CI_PROJECT_NAME.zip *

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]

  script:
    - echo "Deploying code"
    - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$CI_PROJECT_NAME.zip 
  needs:
    - build

